apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: ispn-tasks
spec:
   storageClassName: standard
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 100Mi