apiVersion: v1
kind: ConfigMap
metadata:
   name: cluster-config-filestore
data:
   infinispan-config.xml: >
      <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:13.0 https://infinispan.org/schemas/infinispan-config-13.0.xsd
                                urn:infinispan:server:13.0 https://infinispan.org/schemas/infinispan-server-13.0.xsd"
            xmlns="urn:infinispan:config:13.0"
            xmlns:server="urn:infinispan:server:13.0">
        <cache-container name="default" statistics="true">
            <distributed-cache-configuration name="my-dist-template"
                                            mode="SYNC"
                                            statistics="true">
              <encoding media-type="application/x-protostream"/>
              <memory max-count="1000000"
                      when-full="REMOVE"/>
               <persistence>
                     <file-store/>
               </persistence>
            </distributed-cache-configuration>
        </cache-container>
      </infinispan>